name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    steps:
    - name: Determine Composer cache directory
      shell: bash
      run: "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir)\" >> $GITHUB_ENV"

    steps:
    - name: Cache dependencies installed with Composer
      uses: actions/cache@v2
      with:
        path: "${{ env.COMPOSER_CACHE_DIR }}"
        key: os-${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          os-${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

    - uses: php-actions/composer@v4
      with:
        php_version: 7.4
        composer_version: 2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: check code style
      run: php vendor/bin/php-cs-fixer fix src --dry-run --stop-on-violation
